name: Build and deploy JAR app to Azure Web App - rentalmotorbike

on:
  push:
    branches:
      - feature/testDeployAzure
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target/*.jar'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: java-app
          path: '${{ github.workspace }}/target'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_71980B292B174B9EBFD749BDBEC0D2AA }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_367BF9A3B9894DC986D4EE1BD88C83CB }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6852DD5BA5114BACBD5739B72626BEC4 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'rentalmotorbike'
          slot-name: 'Production'
          package: '${{ github.workspace }}/target/*.jar'